/*
Sortable Data Grid
Copyright © Felix Lindsay 21 November 2017
flindsay@gmail.com
All rights reserved
*/
public with sharing class smdgLabels {
    // attribute simply to force inclusion within package
    public static   List<String> strings = new List<String>{
        Label.smdgAfter,
            Label.smdgBefore,
            Label.smdgContains,
            Label.smdgEnds,
            Label.smdgEquals,
            Label.smdgFalse,
            Label.smdgFiltered,
            Label.smdgFilteredOf,
            Label.smdgGreaterThan,
            Label.smdgLastMonth,
            Label.smdgLastQuarter,
            Label.smdgLastWeek,
            Label.smdgLastYear,
            Label.smdgLessThan,
            Label.smdgNextMonth,
            Label.smdgNextQuarter,
            Label.smdgNextWeek,
            Label.smdgNextYear,
            Label.smdgNoData,
            Label.smdgNotContains,
            Label.smdgNotEquals,
            Label.smdgPage,
            Label.smdgPage_Size,
            Label.smdgStarts,
            Label.smdgThisMonth,
            Label.smdgThisQuarter,
            Label.smdgThisWeek,
            Label.smdgThisYear,
            Label.smdgToday,
            Label.smdgTomorrow,
            Label.smdgTrue,
            Label.smdgYesterday,
            Label.smdgIn,
            Label.smdgAgo
            };

                }